### ISSUE TITLE
 有些对象层级太多，根本打不完 打一定层数就该停止

### ISSUE THREAD

**Issue by tinybright** [pengwei1024/LogUtils#10]
[  at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:32)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.getClassFields(ObjectUtil.java:90)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:41)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.getClassFields(ObjectUtil.java:90)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:41)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:22)
                                                                                                                     at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:29)
                                                                                                                     at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:12)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:32)
                                                                                                                 	at com.apkfuns.logutils.utils.ObjectUtil.getClassFiel
04-22 13:30:02.592 24424-24442/com.protontek.vcare E/vcare/JobFragV1$7.onServicesDiscovered(JobFragV1.java:737): ds(ObjectUtil.java:90)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:41)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.getClassFields(ObjectUtil.java:90)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:41)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:22)
                                                                                                                     at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:29)
                                                                                                                     at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:12)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:32)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.getClassFields(ObjectUtil.java:90)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:41)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:22)
                                                                                                                     at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:29)
                                                                                                                     at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:12)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:32)
                                                                                                                     at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:22)
                                                                                                                     at com.apkfuns.logutils.Logger.logObject(Logger.java:97)
                                                                                                                     at com.apkfuns.logutils.Logger.e(Logger.java:161)
                                                                                                                     at com.apkfuns.logutils.LogUtils.e(LogUtils.java:108)
                                                                                                                     at com.protontek.vcare.ui.module.job.JobFragV1$7.onServicesDiscovered(JobFragV1.java:735)
                                                                                                                     at android.bluetooth.BluetoothGatt$1.onSearchComplete(BluetoothGatt.java:304)
                                                                                                                     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:217)
                                                                                                                     at android.os.Binder.execTransact(Binder.java:453)](url)

**Comment by pengwei1024** [comment]
你是说继承层级吗？

**Comment by tinybright** [comment]
![image](https://cloud.githubusercontent.com/assets/8720949/14734217/761106be-089b-11e6-8d99-84a23596fca6.png)

我不确定。 但是这种是无限循环的

**Comment by pengwei1024** [comment]
1.3.1版本貌似修复了这个问题 @tinybright  你可以试试

**Comment by tinybright** [comment]
如果使用内部类就会这样
class A{
   B b;
   class B{
   }
   public A(){
       b = new B();
   }
}

**Comment by pengwei1024** [comment]
1.4.0版本已经解决这个问题，不是层级多的原因，而是内部类会持有外部类的一个对象，反射获取属性导致死循环了。 @tinybright  感谢[@DrSlark](https://github.com/DrSlark)提供解决方案
