### ISSUE TITLE
java.lang.ClassCastException: char[] cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by GWYloved** [pengwei1024/LogUtils#40]
at com.apkfuns.logutils.utils.ArrayUtil.traverseArray(ArrayUtil.java:97)
                                                                      at com.apkfuns.logutils.utils.ArrayUtil.parseArray(ArrayUtil.java:123)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:59)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.getClassFields(ObjectUtil.java:125)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:63)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.getClassFields(ObjectUtil.java:125)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:63)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:25)
                                                                      at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:31)
                                                                      at com.apkfuns.logutils.parser.CollectionParse.parseString(CollectionParse.java:14)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:54)
                                                                      at com.apkfuns.logutils.utils.ObjectUtil.objectToString(ObjectUtil.java:25)
                                                                      at com.apkfuns.logutils.Logger.logObject(Logger.java:127)
                                                                      at com.apkfuns.logutils.Logger.e(Logger.java:217)
                                                                      at com.apkfuns.logutils.LogUtils.e(LogUtils.java:103)

**Comment by pengwei1024** [comment]
谢谢反馈，我会尽快修复
