### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Stub!

### ISSUE THREAD

**Issue by GWYloved** [pengwei1024/LogUtils#43]
at android.text.TextUtils.isEmpty(TextUtils.java:64)
	at com.apkfuns.logutils.Logger.generateTag(Logger.java:137)
	at com.apkfuns.logutils.Logger.logString(Logger.java:71)
	at com.apkfuns.logutils.Logger.logString(Logger.java:67)
	at com.apkfuns.logutils.Logger.logObject(Logger.java:127)
	at com.apkfuns.logutils.Logger.e(Logger.java:217)
	at com.apkfuns.logutils.LogUtils.e(LogUtils.java:103)

**Comment by GWYloved** [comment]
貌似不支持在main里面打印啊。我以为main里面也可以用

**Comment by pengwei1024** [comment]
你应该已经解决了吧，日志对线程没要求
